export const bikeData = [
  {
    bike_id: "EFKM13",
    lat: 38.897037,
    lon: -77.077373,
    is_reserved: 0,
    is_disabled: 0,
    vehicle_type: "scooter",
    android: "https://deeplink.helbiz.com/startRide?code=EFKM13",
    ios: "https://deeplink.helbiz.com/startRide?code=EFKM13",
  },
  {
    bike_id: "UFF4UG",
    lat: 38.896818,
    lon: -77.070872,
    is_reserved: 0,
    is_disabled: 0,
    vehicle_type: "scooter",
    android: "https://deeplink.helbiz.com/startRide?code=UFF4UG",
    ios: "https://deeplink.helbiz.com/startRide?code=UFF4UG",
  },
  {
    bike_id: "UFFZPP",
    lat: 38.858519,
    lon: -77.054269,
    is_reserved: 0,
    is_disabled: 0,
    vehicle_type: "scooter",
    android: "https://deeplink.helbiz.com/startRide?code=UFFZPP",
    ios: "https://deeplink.helbiz.com/startRide?code=UFFZPP",
  },
  {
    bike_id: "AFKG9P",
    lat: 38.891889,
    lon: -77.083778,
    is_reserved: 0,
    is_disabled: 0,
    vehicle_type: "scooter",
    android: "https://deeplink.helbiz.com/startRide?code=AFKG9P",
    ios: "https://deeplink.helbiz.com/startRide?code=AFKG9P",
  },
  {
    bike_id: "AFKEHX",
    lat: 38.853337,
    lon: -77.05462,
    is_reserved: 0,
    is_disabled: 0,
    vehicle_type: "scooter",
    android: "https://deeplink.helbiz.com/startRide?code=AFKEHX",
    ios: "https://deeplink.helbiz.com/startRide?code=AFKEHX",
  },
  {
    bike_id: "AFKEMJ",
    lat: 38.879818,
    lon: -77.108482,
    is_reserved: 0,
    is_disabled: 0,
    vehicle_type: "scooter",
    android: "https://deeplink.helbiz.com/startRide?code=AFKEMJ",
    ios: "https://deeplink.helbiz.com/startRide?code=AFKEMJ",
  },
];
export const FETCH_URL = "https://announcekit-cdn.s3.amazonaws.com/bikes.json";
